var chineseProducts = {
    fileSharing: [{ "name": 'SHAREit' }, { "name": 'Xender' }],
    scanning: [{ "name": 'CamScanner' }],
    security: [{ "name": 'Safe Security' }],
    social: [{ "name": 'Tik Tok' }, { "name": 'Helo' }, { "name": 'Bigo' }, { "name": 'Vigo' }, { "name": 'VMate' }, { "name": 'Kwai' }],
    chatting: [{ "name": 'WeChat' }, { "name": 'QQ International' }],
    mail: [{ "name": 'QQMail' }, { "name": 'Mail Master' }],
    videoEditing: [{ "name": 'Viva Video' }],
    photoEditing: [{ "name": 'Beauty Plus' }],
    music: [{ "name": 'QQ Music' }, { "name": 'Resso' }],
    browsers: [{ "name": 'APUS Browser' }, { "name": 'UC Browser' }],
    news: [{ "name": 'NewsDog' }, { "name": 'UC News' }],
    utility: [{ "name": 'AppLock' }, { "name": 'Super Clean' }, { "name": 'Parallel Space' }],
    finance: [{ "name": 'WeChat Pay' }],
    videoCalling: [{ "name": 'WeChat' }, { "name": 'QQ International' }],
    shopping: [{ "name": 'Alibaba' }, { "name": 'Club Factory' }, { "name": 'Ali Express' }, { "name": 'Shein' }, { "name": 'Romwe' }],
    games: [
        { "name": 'PUBG' },
        { "name": 'Clash of Kings' },
        { "name": 'Clash of Clans' },
        { "name": 'Call of Duty Mobile' },
        { "name": 'Ludo' },
        { "name": 'Boom Beach' },
        { "name": 'Hay Day' },
    ],
    office: [{ "name": 'WPS Office' }],
};

var indianProducts = {
    social: [{
            name: 'Roposo',
            description: '',
            ios: 'https://apps.apple.com/in/app/roposo-watch-make-fun-videos/id950273328',
            android: 'https://play.google.com/store/apps/details?id=com.roposo.android',
            indian: true,
        },
        {
            name: 'Chingari',
            description: '',
            ios: 'https://apps.apple.com/in/app/chingari/id1450361582',
            android: 'https://play.google.com/store/apps/details?id=io.chingari.app&hl=en_IN',
            indian: true,
        },
        {
            name: 'Pixalive',
            description: '',
            ios: 'https://apps.apple.com/in/app/pixalive/id1491966281',
            android: 'https://play.google.com/store/apps/details?id=com.pixalive&hl=en',
            indian: true,
        },
        {
            name: 'Bolo Indya',
            description: '',
            ios: '',
            android: 'https://play.google.com/store/apps/details?id=com.boloindya.boloindya',
            indian: true,
        },
        {
            name: 'ShareChat',
            description: '',
            ios: 'https://apps.apple.com/in/app/sharechat-videos-status/id1440640105',
            android: 'https://play.google.com/store/apps/details?id=in.mohalla.sharechat',
            indian: true,
        },
    ],
    office: [],
    chatting: [{
            name: 'JioChat',
            description: '',
            ios: 'https://apps.apple.com/in/app/jiochat-video-messenger/id981918884',
            android: 'https://play.google.com/store/apps/details?id=com.jiochat.jiochatapp',
            india: true,
        },
        {
            name: 'Pixalive',
            description: '',
            ios: 'https://apps.apple.com/in/app/pixalive/id1491966281',
            android: 'https://play.google.com/store/apps/details?id=com.pixalive&hl=en',
            indian: true,
        },
        {
            name: 'ShareChat',
            description: '',
            ios: 'https://apps.apple.com/in/app/sharechat-videos-status/id1440640105',
            android: 'https://play.google.com/store/apps/details?id=in.mohalla.sharechat',
            indian: true,
        },
        {
            name: 'Hike',
            description: '',
            ios: 'https://apps.apple.com/us/app/hike-sticker-chat-hikemoji/id568038211',
            android: 'https://play.google.com/store/apps/details?id=com.hike.chat.stickers',
            indian: true,
        },
    ],
    music: [{
            name: 'Gaana',
            description: '',
            ios: 'https://apps.apple.com/in/app/gaana-music-songs-podcasts/id585270521',
            android: 'https://play.google.com/store/apps/details?id=com.gaana',
            india: true,
        },
        {
            name: 'Jio Saavn',
            description: '',
            ios: 'https://apps.apple.com/in/app/jiosaavn-music-podcasts/id441813332',
            android: 'https://play.google.com/store/apps/details?id=com.jio.media.jiobeats',
            indian: true,
        },
        {
            name: 'Wynk',
            description: '',
            ios: 'https://apps.apple.com/lk/app/wynk-music-songs-downloads/id845083955',
            android: 'https://play.google.com/store/apps/details?id=com.bsbportal.music',
            indian: true,
        },
    ],
    news: [{
            name: 'Inshorts',
            description: '',
            ios: 'https://apps.apple.com/us/app/inshorts/id892146527',
            android: 'https://play.google.com/store/apps/details?id=com.nis.app',
            india: true,
        },
        {
            name: 'DailyHunt',
            description: '',
            ios: 'https://apps.apple.com/in/app/dailyhunt-formerly-newshunt/id338525188',
            android: 'https://play.google.com/store/apps/details?id=com.eterno',
            indian: true,
        },
    ],
    shopping: [{
            name: 'Tata CLiQ',
            description: '',
            ios: 'https://apps.apple.com/us/app/tata-cliq-online-shopping-app/id1101619385',
            android: 'https://play.google.com/store/apps/details?id=com.tul.tatacliq',
            indian: true,
        },
        {
            name: 'Flipkart',
            description: '',
            ios: 'https://apps.apple.com/in/app/flipkart-online-shopping-app/id742044692',
            android: 'https://play.google.com/store/apps/details?id=com.flipkart.android&hl=en_IN',
            india: true,
        },
        {
            name: 'Snapdeal',
            description: '',
            ios: 'https://play.google.com/store/apps/details?id=com.snapdeal.main',
            android: 'https://play.google.com/store/apps/details?id=com.snapdeal.main',
            india: true,
        },
        {
            name: 'PayTM',
            description: '',
            ios: 'https://apps.apple.com/in/app/mobile-recharge-bill-payments/id473941634',
            android: 'https://play.google.com/store/apps/details?id=net.one97.paytm',
            india: true,
        },
        {
            name: 'Myntra',
            description: '',
            ios: 'https://apps.apple.com/al/app/myntra-fashion-shopping-app/id907394059',
            android: 'https://play.google.com/store/apps/details?id=com.myntra.android&hl=en_IN',
            india: true,
        },
        {
            name: 'IndiaMart',
            description: '',
            ios: 'https://apps.apple.com/in/app/indiamart-buy-sell-products/id668561641',
            android: 'https://play.google.com/store/apps/details?id=com.indiamart.m&hl=en_IN',
            indian: true,
        },
        {
            name: 'Shopclues',
            description: '',
            ios: 'https://apps.apple.com/il/app/shopclues/id994486085',
            android: 'https://play.google.com/store/apps/details?id=com.shopclues&hl=en_IN',
            india: true,
        },
        {
            name: 'Udaan',
            description: '',
            ios: 'https://apps.apple.com/in/app/udaan/id1224098850',
            android: 'https://play.google.com/store/apps/details?id=com.udaan.android&hl=en_IN',
            indian: true,
        },
        {
            name: 'Ajio',
            description: '',
            ios: 'https://apps.apple.com/us/app/ajio-online-shopping-app/id1113425372',
            android: 'https://play.google.com/store/search?q=ajio&c=apps&hl=en_IN',
            india: true,
        },
        {
            name: 'Limeroad',
            description: '',
            ios: 'https://apps.apple.com/jo/app/limeroad-shopping/id890803320',
            android: 'https://play.google.com/store/apps/details?id=com.shopping.limeroad&hl=en_IN',
            indian: true,
        },
    ],
    browsers: [{
            name: 'Jio Browser',
            description: '',
            ios: '',
            android: 'https://play.google.com/store/apps/details?id=com.jio.web&hl=en_IN',
            india: true,
        },
        {
            name: 'Bharat Browser',
            description: '',
            ios: '',
            android: 'https://play.google.com/store/apps/details?id=com.bharat.browser',
            indian: true,
        },
        {
            name: 'Epic Browser',
            description: '',
            ios: 'https://apps.apple.com/us/app/epic-privacy-browser-w-vpn/id1502032811',
            android: 'https://play.google.com/store/apps/details?id=com.epic.browser&hl=en_IN',
            indian: true,
        },
    ],
    security: [{
            name: 'JioSecurity',
            description: '',
            ios: 'https://apps.apple.com/in/app/jiosecurity/id1140892768',
            android: 'https://play.google.com/store/apps/details?id=com.reliancejio.mobilesecurity&hl=en_IN',
            india: true,
        },
        {
            name: 'QuickHeal',
            description: '',
            ios: 'https://apps.apple.com/in/app/quick-heal-optimizer/id1025007234',
            android: 'https://play.google.com/store/apps/details?id=com.quickheal.platform&hl=en_IN',
            indian: true,
        },
    ],
    finance: [{
            name: 'BHIM',
            description: '',
            ios: 'https://apps.apple.com/in/app/bhim-making-india-cashless/id1200315258',
            android: 'https://play.google.com/store/apps/details?id=in.org.npci.upiapp',
            india: true,
        },
        {
            name: 'Mobikwik',
            description: '',
            ios: 'https://apps.apple.com/jo/app/mobikwik-recharge-bill-pay/id600002523',
            android: 'https://play.google.com/store/apps/details?id=com.mobikwik_new',
            india: true,
        },
        {
            name: 'PayTM',
            description: '',
            ios: 'https://apps.apple.com/in/app/mobile-recharge-bill-payments/id473941634',
            android: 'https://play.google.com/store/apps/details?id=net.one97.paytm',
            india: true,
        },
        {
            name: 'PhonePe',
            description: '',
            ios: 'https://apps.apple.com/in/app/phonepe-indias-payments-app/id1170055821',
            android: 'https://play.google.com/store/apps/details?id=com.phonepe.app',
            india: true,
        },
    ],
    videoCalling: [{
        name: 'Say Namaste',
        description: '',
        ios: 'https://apps.apple.com/in/app/say-namaste-video-conferencing/id1508559464',
        android: 'https://play.google.com/store/apps/details?id=com.inscripts.namaste',
        india: true,
    }, ],
    utility: [],
    games: [{
            name: 'Ludo King',
            description: '',
            ios: 'https://apps.apple.com/jm/app/ludo-king/id993090598',
            android: 'https://play.google.com/store/apps/details?id=com.ludo.king&hl=en_IN',
            india: true,
        },
        {
            name: 'Sudoku King',
            description: '',
            ios: 'https://apps.apple.com/us/app/sudoku-king/id1498907458',
            android: 'https://play.google.com/store/apps/details?id=com.gametion.sudokuking',
            india: true,
        },
        {
            name: 'Carrom King',
            description: '',
            ios: 'https://apps.apple.com/in/app/carrom-king/id1227693816',
            android: 'https://play.google.com/store/apps/details?id=com.git.carromking',
            india: true,
        },
        {
            name: 'Guardians of the Skies',
            description: '',
            ios: 'https://apps.apple.com/in/app/guardians-of-the-skies/id903373261',
            android: 'https://play.google.com/store/apps/details?id=com.threye.iaf.gots&hl=en_IN',
            indian: true,
        },
        {
            name: 'Baahubali The Game',
            description: '',
            ios: 'https://apps.apple.com/us/app/baahubali-the-game-official/id1213305979',
            android: 'https://play.google.com/store/apps/details?id=com.bahubali.game&hl=en_IN',
            indian: true,
        },
        {
            name: 'World Cricket Championship',
            description: '',
            ios: 'https://apps.apple.com/us/app/world-cricket-championship-2/id1025281689',
            android: 'https://play.google.com/store/apps/details?id=com.nextwave.wcc2&hl=en_IN',
            indian: true,
        },
        {
            name: 'World Table Tennis Champs',
            description: '',
            ios: 'https://apps.apple.com/us/app/world-table-tennis-champs/id1386609664',
            android: 'https://play.google.com/store/apps/details?id=com.nextwave.wttcpingpong&hl=en_IN',
            indian: true,
        },
        {
            name: 'Real Carrom',
            description: '',
            ios: 'https://apps.apple.com/us/app/real-carrom/id1105859833',
            android: 'https://play.google.com/store/apps/details?id=com.nextwave.realcarrom',
            indian: true,
        },
    ],
    fileSharing: [{
        name: 'JioSwitch',
        description: '',
        ios: 'https://apps.apple.com/in/app/jioswitch-transfer-share-files/id921382666',
        android: 'https://play.google.com/store/apps/details?id=com.reliance.jio.jioswitch&hl=en_IN',
        india: true,
    }, ],
    videoEditing: [],
    photoEditing: [{
        name: 'Indian Selfie Camera',
        description: '',
        ios: '',
        android: 'https://play.google.com/store/apps/details?id=com.appbreakers.selfiecamera&hl=en_IN',
        india: true,
    }, ],
    scanning: [{
        name: 'Kaagaz',
        description: '',
        ios: '',
        android: 'https://play.google.com/store/apps/details?id=kaagaz.scanner.docs.pdf&hl=en_IN',
        india: true,
    }, ],
    mail: [{
            name: 'Zoho Mail',
            description: '',
            ios: 'https://apps.apple.com/us/app/zoho-mail-email-and-calendar/id909262651',
            android: 'https://play.google.com/store/apps/details?id=com.zoho.mail&hl=en_IN',
            india: true,
        },
        {
            name: 'Data Mail',
            description: '',
            ios: 'https://apps.apple.com/us/app/datamail/id1149220951?ls=1',
            android: 'https://play.google.com/store/apps/details?id=com.datainfosys.datamail',
            india: true,
        },
    ],
};

var otherProducts = {
    social: [{
            name: 'Lasso',
            description: '',
            ios: 'https://apps.apple.com/us/app/lasso-short-fun-videos/id1436534917',
            android: 'https://play.google.com/store/apps/details?id=com.lassoworkforce.lassov4&hl=en_IN',
            indian: false,
        },
        {
            name: 'Firework',
            description: '',
            ios: 'https://apps.apple.com/us/app/firework-best-short-videos/id1359999964',
            android: 'https://play.google.com/store/apps/details?id=com.loopnow.kamino&hl=en_IN',
            indian: false,
        },
        {
            name: 'Dubsmash',
            description: '',
            ios: 'https://apps.apple.com/us/app/dubsmash-videos-music/id918820076',
            android: 'https://play.google.com/store/apps/details?id=com.mobilemotion.dubsmash&hl=en_IN',
            indian: false,
        },
    ],
    office: [{
            name: 'Microsoft Office',
            description: '',
            ios: 'https://apps.apple.com/us/app/microsoft-office/id541164041',
            android: 'https://play.google.com/store/apps/details?id=com.microsoft.office.officehubrow',
            indian: false,
        },
        {
            name: 'Google Docs',
            description: '',
            ios: 'https://apps.apple.com/us/app/google-docs-sync-edit-share/id842842640',
            android: 'https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.docs',
            indian: false,
        },
        {
            name: 'Google Sheets',
            description: '',
            ios: 'https://apps.apple.com/us/app/google-sheets/id842849113',
            android: 'https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.sheets',
            indian: false,
        },
        {
            name: 'Google Slides',
            description: '',
            ios: 'https://apps.apple.com/us/app/google-slides/id879478102',
            android: 'https://play.google.com/store/apps/details?id=com.google.android.apps.docs.editors.slides',
            indian: false,
        },
    ],
    games: [{
        name: 'Fortnite',
        description: '',
        ios: 'https://apps.apple.com/us/app/fortnite/id1261357853',
        android: 'https://play.google.com/store/apps/details?id=com.epicgames.fortnite&hl=en_IN',
        indian: false,
    }, ],
    shopping: [{
        name: 'Amazon',
        description: '',
        ios: 'https://apps.apple.com/us/app/amazon-shopping-made-easy/id297606951',
        android: 'https://play.google.com/store/apps/details?id=in.amazon.mShop.android.shopping&hl=en_IN',
        india: false,
    }, ],
    music: [{
        name: 'Spotify',
        description: '',
        ios: 'https://apps.apple.com/us/app/spotify-music-and-podcasts/id324684580',
        android: 'https://play.google.com/store/apps/details?id=com.spotify.music&hl=en_IN',
        india: false,
    }, ],
    fileSharing: [{
        name: 'Files by Google',
        description: '',
        ios: '',
        android: 'https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files&hl=en_IN',
        india: false,
    }, ],
    news: [],
    scanning: [{
            name: 'Adobe Scan',
            description: '',
            ios: 'https://apps.apple.com/sr/app/adobe-scan-pdf-card-scanner/id1199564834',
            android: 'https://play.google.com/store/apps/details?id=com.adobe.scan.android&hl=en_IN',
            india: false,
        },
        {
            name: 'Microsoft Lens',
            description: '',
            ios: 'https://apps.apple.com/us/app/microsoft-office-lens-pdf-scan/id975925059',
            android: 'https://play.google.com/store/apps/details?id=com.microsoft.office.officelens&hl=en_IN',
            india: false,
        },
        {
            name: 'PhotoScan by Google',
            description: '',
            ios: 'https://apps.apple.com/us/app/photoscan-by-google-photos/id1165525994',
            android: 'https://play.google.com/store/apps/details?id=com.google.android.apps.photos.scanner&hl=en_IN',
            india: false,
        },
    ],
    security: [{
            name: 'Avast Antivirus',
            description: '',
            ios: 'https://apps.apple.com/us/app/avast-security-privacy/id1276551855',
            android: 'https://play.google.com/store/apps/details?id=com.avast.android.mobilesecurity&hl=en_IN',
            india: false,
        },
        {
            name: 'Norton Antivirus',
            description: '',
            ios: 'https://apps.apple.com/us/app/norton-mobile-security/id1278474169',
            android: 'https://play.google.com/store/apps/details?id=com.symantec.mobilesecurity&hl=en_IN',
            india: false,
        },
    ],
    utility: [{
            name: 'Norton Applock',
            description: '',
            ios: '',
            android: 'https://play.google.com/store/apps/details?id=com.symantec.applock&hl=en_IN',
            india: false,
        },
        {
            name: 'Norton Clean',
            description: '',
            ios: '',
            android: 'https://play.google.com/store/apps/details?id=com.symantec.cleansweep&hl=en_IN',
            india: false,
        },
        {
            name: 'Clone App',
            description: '',
            ios: '',
            android: 'https://play.google.com/store/apps/details?id=com.cloneapp.parallelspace.dualspace',
            india: false,
        },
        {
            name: 'DO Multiple Accounts',
            description: '',
            ios: '',
            android: 'https://play.google.com/store/apps/details?id=do.multiple.cloner',
            india: false,
        },
    ],
    finance: [{
        name: 'Google Pay',
        description: '',
        ios: 'https://apps.apple.com/us/app/google-pay/id575923525',
        android: 'https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.paisa.user',
        india: false,
    }, ],
    videoCalling: [{
            name: 'Google Duo',
            description: '',
            ios: 'https://apps.apple.com/us/app/google-duo/id1096918571',
            android: 'https://play.google.com/store/apps/details?id=com.google.android.apps.tachyon&hl=en_IN',
            india: false,
        },
        {
            name: 'Google Meet',
            description: '',
            ios: 'https://apps.apple.com/us/app/google-meet/id1013231476',
            android: 'https://play.google.com/store/apps/details?id=com.google.android.apps.meetings&hl=en_IN',
            india: false,
        },
        {
            name: 'Messenger',
            description: '',
            ios: 'https://apps.apple.com/in/app/messenger/id454638411',
            android: 'https://play.google.com/store/apps/details?id=com.facebook.orca&hl=en_IN',
            india: false,
        },
    ],
    browsers: [{
            name: 'Google Chrome',
            description: '',
            android: 'https://play.google.com/store/apps/details?id=com.android.chrome&hl=en_IN',
            ios: 'https://apps.apple.com/in/app/google-chrome/id535886823',
            india: false,
        },
        {
            name: 'Mozilla Firefox',
            description: '',
            ios: 'https://apps.apple.com/ao/app/firefox-private-safe-browser/id989804926',
            android: 'https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en_IN',
            india: false,
        },
        {
            name: 'Microsoft Edge',
            description: '',
            ios: 'https://apps.apple.com/us/app/microsoft-edge/id1288723196',
            android: 'https://play.google.com/store/apps/details?id=com.microsoft.emmx&hl=en_IN',
            india: false,
        },
    ],
    mail: [{
            name: 'Outlook',
            description: '',
            ios: 'https://apps.apple.com/us/app/microsoft-outlook/id951937596',
            android: 'https://play.google.com/store/apps/details?id=com.microsoft.office.outlook&hl=en_IN',
            india: false,
        },
        {
            name: 'Yahoo Mail',
            description: '',
            ios: 'https://apps.apple.com/us/app/yahoo-mail-organized-email/id577586159',
            android: 'https://play.google.com/store/apps/details?id=com.yahoo.mobile.client.android.mail&hl=en_IN',
            india: false,
        },
        {
            name: 'Gmail',
            description: '',
            ios: 'https://apps.apple.com/us/app/gmail-email-by-google/id422689480',
            android: 'https://play.google.com/store/apps/details?id=com.google.android.gm&hl=en_IN',
            india: false,
        },
    ],
    chatting: [{
            name: 'WhatsApp',
            description: '',
            ios: 'https://apps.apple.com/in/app/whatsapp-messenger/id310633997',
            android: 'https://play.google.com/store/apps/details?id=com.whatsapp&hl=en_IN',
            india: false,
        },
        {
            name: 'Messenger',
            description: '',
            ios: 'https://apps.apple.com/in/app/messenger/id454638411',
            android: 'https://play.google.com/store/apps/details?id=com.facebook.orca&hl=en_IN',
            india: false,
        },
        {
            name: 'Telegram',
            description: '',
            ios: 'https://apps.apple.com/us/app/telegram-messenger/id686449807',
            android: 'https://play.google.com/store/apps/details?id=org.telegram.messenger&hl=en_IN',
            india: false,
        },
    ],
    videoEditing: [{
            name: 'Adobe Premiere Rush',
            description: '',
            ios: 'https://apps.apple.com/us/app/adobe-premiere-rush-for-video/id1188753863',
            android: 'https://play.google.com/store/apps/details?id=com.adobe.premiererush.videoeditor&hl=en_IN',
            india: false,
        },
        {
            name: 'Quik',
            description: '',
            ios: 'https://apps.apple.com/us/app/quik-gopro-video-editor/id694164275',
            android: 'https://play.google.com/store/apps/details?id=com.stupeflix.replay&hl=en_IN',
            india: false,
        },
    ],
    photoEditing: [{
            name: 'Snapseed',
            description: '',
            ios: 'https://apps.apple.com/us/app/snapseed/id439438619',
            android: 'https://play.google.com/store/apps/details?id=com.niksoftware.snapseed&hl=en_IN',
            india: false,
        },
        {
            name: 'Prisma',
            description: '',
            ios: 'https://apps.apple.com/us/app/prisma-photo-editor/id1122649984',
            android: 'https://play.google.com/store/apps/details?id=com.neuralprisma&hl=en_IN',
            india: false,
        },
        {
            name: 'PicsArt',
            description: '',
            ios: 'https://apps.apple.com/us/app/picsart-photo-video-editor/id587366035',
            android: 'https://play.google.com/store/apps/details?id=com.picsart.studio&hl=en_IN',
            india: false,
        },
        {
            name: 'Adobe Photoshop Express',
            description: '',
            ios: 'https://apps.apple.com/kw/app/photoshop-express-photo-editor/id331975235',
            android: 'https://play.google.com/store/apps/details?id=com.adobe.psmobile&hl=en_IN',
            india: false,
        },
    ],
};

//Run these together to update tags in db.json from https://gist.githubusercontent.com/mishra-ankit/6fb2126e922a1a58014c6bd76b80efa1/raw/90975dd1665844d3e7b4beec30db9c245e5c2fd4/productsDB.js

//1. Create company to tags object
var companyToTags = {}
var jsons = [chineseProducts, indianProducts, otherProducts];
for (var i in jsons) {
    var json = jsons[i];
    for (var prop in json) {
        for (var x in json[prop]) {
            var comp = json[prop][x]["name"];
            console.log(x + " " + comp);
            if (companyToTags[comp]) {
                companyToTags[comp].push(prop);
            } else {
                companyToTags[comp] = [];
                companyToTags[comp].push(prop);
            }
        }
    }
}


//2. update DB.json with tags
//var db = <db.json array>
for (var i in db) {
    var comp = db[i]["name"];
    if (companyToTags[comp]) {
        db[i]["tags"] = companyToTags[comp];
    }
}
copy(db);